// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetPrayerTimes(arg1:string,arg2:string):Promise<main.PrayerResult>;

export function GetQibla(arg1:number,arg2:number):Promise<number>;

export function GetQuranSurah(arg1:number):Promise<main.SurahDetail>;

export function GetQuranSurahs():Promise<Array<main.Surah>>;

export function SendNotification(arg1:string,arg2:string):Promise<void>;

export function SetWidgetMode(arg1:boolean):Promise<void>;
