// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPrayerTimes(arg1, arg2) {
  return window['go']['main']['App']['GetPrayerTimes'](arg1, arg2);
}

export function GetQibla(arg1, arg2) {
  return window['go']['main']['App']['GetQibla'](arg1, arg2);
}

export function GetQuranSurah(arg1) {
  return window['go']['main']['App']['GetQuranSurah'](arg1);
}

export function GetQuranSurahs() {
  return window['go']['main']['App']['GetQuranSurahs']();
}

export function SendNotification(arg1, arg2) {
  return window['go']['main']['App']['SendNotification'](arg1, arg2);
}

export function SetWidgetMode(arg1) {
  return window['go']['main']['App']['SetWidgetMode'](arg1);
}
